### PR TITLE
Add create and get function to base service

### PR DESCRIPTION
**Pull request by dansel91**
@imscaradh please review, merge

### CODE REVIEW

**Comment by imscaradh** [comment]
@dansel91 please set all the methods in `BaseService` to protected :innocent:

**Comment by dansel91** [comment]
Done on current work. I forgot our last talk about that
Am 11.11.2015 11:42 schrieb "Pascal Zingg" <notifications@github.com>:

**Comment by ndalliard** [comment]
Shouldn't we just merge if the code coverage is okay?

**Comment by imscaradh** [comment]
@dansel91 as @ndalliard  mentioned, the codecov isn't ok, please add tests for the new methods

**Comment by dansel91** [comment]
Jajaja
Am 12.11.2015 11:45 schrieb "Pascal Zingg" <notifications@github.com>:

**Pull request closed without merging**
