### PR TITLE
dh-DBSchema

### PR DESCRIPTION
**Pull request by dansel91**
Extended BaseService and changed DB schema
@Tschanzt Review?

### CODE REVIEW

**Comment by Tschanzt** [comment]
@dansel91 Could you please fix the tests?

**Comment by dansel91** [comment]
@Tschanzt The tests work perfectly. But no code is provided yet. So? Should i set the NotImplementedException Tag?

**Comment by Tschanzt** [comment]
@dansel91 Yes if the code isn't implemented yet you should.

**Comment by dansel91** [comment]
...  -.-

**Pull request merged**
