### PR TITLE
Added Basic Login Window (Redirect To Calendar)

### PR DESCRIPTION
**Pull request by ndalliard**
This is a really basic login functionality.

The transition when you click the "Login-Button" isn't that smooth.

@imscaradh : Maybe you can use this to make the settings View. Add a gotoSettings() method in the Main.java file. Just an idea.

Oh and do I have to insert the Copyright also into the .fxml files?

### CODE REVIEW

**Comment by imscaradh** [comment]
The rough transition occurs during the exchange of the fxml files. I think it should be possible that we can switch the whole scene with help of the main stage and implement a suitable transition animation.

It isn't necessary to insert the copyright header into resource files. The Checkstyle Plugin checks Java source files only.

**Comment by ndalliard** [comment]
I simplified the code a lot. I am not sure if it is okay to load the Calendar itself in the LoginController. Maybe not the best design approach?!

The rough transition should not be caused by an fxml file cause the Calendar itself doesn't even load an .fxml file. Or do I overlook something? Look at the code, as I said, I deleted a lot lines which weren't necessary.

Still no idea how to implement a nice transition betweent the two Scenes.

**Comment by imscaradh** [comment]
Please checkout my solution on the following branch: https://github.com/imscaradh/srs/tree/pz-generalluisettings

**Comment by ndalliard** [comment]
Ah, that looks great. I will use your classes and add the login functionallity based on your structure tomorrow morning in school.

**Comment by ndalliard** [comment]
I took the structure from @imscaradh and now the login works smoothly. Thanks! :+1:

**Comment by imscaradh** [comment]
Seems to be ok :+1:

**Pull request merged**
