### PR TITLE
Added List Of Developers

### PR DESCRIPTION
**Pull request by ndalliard**
We now use a doc branch to modify any changes to the documentation in the future.

@dansel91 What do you think about your image?

### CODE REVIEW

**Comment by ndalliard** [comment]
Because this is a change in the pom.xml file everyone ( @Tschanzt @imscaradh @dansel91 @iSchoggiPanzer ) should make a `mvn package site` after the merge of this pull request.

**Comment by Tschanzt** [comment]
@ndalliard Could you remove the timezones? Because they will be wrong in a month.

**Comment by ndalliard** [comment]
@Tschanzt Done. :+1:

**Comment by Tschanzt** [comment]
:+1:

**Pull request merged**
